// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://msgldvqyyaxohdelhtaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zZ2xkdnF5eWF4b2hkZWxodGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDY3NTYsImV4cCI6MjA2NjM4Mjc1Nn0.KZ9_NsZ_mPlMohmAc85JlIwdaWll6RSK8G8_bLNmz_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);